version: "3.4"

services:
  epicnfts:
    image: epicnfts
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ALCHEMY_RINKEBY_API_URL=${ALCHEMY_RINKEBY_API_URL}
      - PRIVATE_ACCOUNT_KEY=${PRIVATE_ACCOUNT_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
